spring:
  data:
    redis:
      host: valkey-9b36d75-yjshin-9d26.b.aivencloud.com
      port: 28512
      username: default
      password: ${DB_PASSWORD}
      ssl:
        enabled: true





# JWT
jwt:
  secret: 616de035626742756277135514960e0a
  # 만료일 설정
  # 1분 테스트용
  access-token-expiration: 60000
  # 5분 테스트용
  refresh-token-expiration: 300000



